using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSharp.Problems.Arrays_and_Hashing
{
    // You are given two strings s and t.

    // String t is generated by random shuffling string s and then add one more letter at a random position.

    // Return the letter that was added to t.

    // Example 1
    // Input: s = "abcd", t = "abcde"
    // Output: 'e'

    // Example 2
    // Input: s = "", t = "y"
    // Output: 'y'
    public class FindTheDifference
    {
        // Time complexity: O(N)
        // Space complexity: O(1)
        public char FindDifference(string s, string t)
        {
            int[] freq = new int[26];

            for (int i = 0; i < s.Length; i++)
            {
                freq[s[i] - 'a']++;
            }

            for (int i = 0; i < t.Length; i++)
            {
                freq[t[i] - 'a']--;
                if (freq[t[i] - 'a'] < 0)
                {
                    return t[i];
                }
            }

            return ' ';
        }
    }
}
